### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Maxoso41** [cooleGruppe/Magical-Imagery#11]
Als Kunde möchte ich mein Feedback zum Produkt geben können, damit ich anderen Nutzern eine Empfehlung geben kann. 

- [x] Option um nach einem Kauf ein Feedback zu erstellen
- [x] Eingabefeld für Kommentar
- [x] Bewertung mit Sternen

**Comment by Egomann88** [comment]
Nur Kommentare unter dem Produkt sind möglich, keine direkten Bewertungen
