### ISSUE TITLE
Backups

### ISSUE THREAD

**Issue by Maxoso41** [cooleGruppe/Magical-Imagery#3]
Als Administrator möchte ich regelmässige Backups des Systems erstellen lassen, um im Falle eines Datenverlusts schnell wiederherstellen zu können.

- [ ] Option um Zeitraum auszuwählen
- [ ] Option um Anzahl von vorherigen Backups, welche behalten werden sollen, einzustellen.
- [ ] Automatische Erstellung von Backups mit ausgewählten Einstellungen

**Comment by Egomann88** [comment]
Dieses Repo hat einen Service, der jede Woche einen SQL Export und diesen an ein seperates Repo mit REST-API schickt?

**Comment by Egomann88** [comment]
New: Auf Einstellungen Seite, soll ein Backup Button gemacht werden, welcher seinen gesamten SQL-Export macht. Allfällig wird dieser an irgendeinen Provider geschickt.
