### ISSUE TITLE
Produkt anpassen

### ISSUE THREAD

**Issue by Maxoso41** [cooleGruppe/Magical-Imagery#7]
Als Kunde möchte ich bei einem Artikel die Option haben, mehrere Grössen und Lizenzmodelle auswählen zu können, damit dieses besser meinen Bedürfnissen entspricht.

- [x] Option um ein Produkt anpassen zu können
- [x] Hinzufügen von Verschiedenen Grösse-Optionen
- [x] Auswahl verschiedener Lizenzmodelle

**Comment by Egomann88** [comment]
Feature kicked.

Grösse und Lizenz sind fest und können nicht geändert werden.
